### ISSUE TITLE
Errors in console when trying to use Discovery App online

### ISSUE THREAD

**Issue by simonexmachina** [contentful/discovery-app-react#2]
I get the following errors when I try to use the app:

```
main.bundle.js:20 Uncaught (in promise) TypeError: Cannot read property 'url' of undefined
main.bundle.js:3 Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
main.bundle.js:25 Uncaught TypeError: Cannot read property 'componentWillReceiveProps' of null
```

**Comment by simonexmachina** [comment]
On investigation I suspected that it was because the content doesn't have a media asset. I created the media asset and it fixed the problem.

**Comment by Khaledgarbaya** [comment]
Hi @aexmachina , sorry for the late response.
Can you please give us more details on what did happen exactly like step to reproduce this issue.
we'll be glad to help.
Best,
Khaled
