### ISSUE TITLE
Access Keys

### ISSUE THREAD

**Issue by tomhoad** [contentful/discovery-app-react#26]
Should we be concerned that access keys are available to anyone on the client?

https://github.com/contentful/discovery-app-react/blob/master/src/main.js#L20

**Comment by Khaledgarbaya** [comment]
Hi @tomhoad,
The Contentful Discovery web app gives you a quick and easy way to preview your content on a web environment, and explore the contents of your Spaces.
In general, you should not expose your credentials the API key gives a read-only access so they won't be able to change anything in your space
